### ISSUE TITLE
History not working

### ISSUE THREAD

**Issue by cajureba** [ReVanced-Extended-Community/Patches-Documentation#8]
Hello
All videos watched are not added to history
Seems that YT changed it and Revanced Extended is not working properly

**Comment by KobeW50** [comment]
Hi there. Unfortunately the dev is no longer updating ReVanced Extended (RVX). However, this issue was fixed in the ReX project (which is a fork of RVX from a different developer)

See [this post](https://www.reddit.com/r/revancedextended/comments/1b4vj54/history_problem_solved/) or the [ReX wiki](https://github.com/YT-Advanced/revanced-documentation) for instructions to patch ReX.
